### ISSUE TITLE
QUESTION: when/why would the nomad provider "timeout" from Terraform's perspective?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform-provider-nomad#198] opened 2021-01-21 20:13 UTC
Hi there,

I've seen the nomad provider timeout reaching out to a nomad server, but until today, I hadn't ever seen the provider fail to respond to Terraform and error out like this:

![image](https://user-images.githubusercontent.com/10122937/105406565-7f583f80-5c24-11eb-839e-58f5e3af0f14.png)

I don't have enough info for a bug report w/ reproduction, so I'm primarily looking to ask under what conditions you would expect the nomad provider to fail like this.

I've seen this with versions `1.4.9` and `1.4.11` of the nomad provider, both using Terraform `0.11.13`.

**Comment by lgfa29** [comment] 2021-01-21 20:38
Hi @ketzacoatl,

I don't recall ever running into this problem...from the screenshot it seems to have happened during a `terraform apply`, but does it also happen on `terraform plan`?

Also, would it be possible to provide how many resources are being managed by the Nomad provider?

Running something like `terraform state list | grep nomad_ | wc -l` would give a good estimate.

**Comment by cgbaker** [comment] 2021-01-21 21:00
Hi @ketzacoatl , running `TF_LOG=DEBUG terraform plan` may indicate where the breakdown is happening.

**Comment by ketzacoatl** [comment] 2021-01-21 21:00
Hello @lgfa29,

> I don't recall ever running into this problem...from the screenshot it seems to have happened during a terraform apply, but does it also happen on terraform plan?
Yes, that's during a `terraform apply`. This is during a CI pipeline, and the plan runs before hand and passes ok.

> Also, would it be possible to provide how many resources are being managed by the Nomad provider?
In this case it's small, like 3 I think. A local file, a nomad_job, and a cloudwatch resource, then some data sources and a template.

**Comment by ketzacoatl** [comment] 2021-01-21 21:05
@cgbaker,

> running TF_LOG=DEBUG terraform plan may indicate where the breakdown is happening.

IDK that I can reliably reproduce this in the environment/CI pipeline where I've seen it (rerunning the job, there is no timeout). I've seen it happen more than once today.

I am a bit loaded up ATM, but I would like to try to create a minimal repro. That said, I'm not confident I'll be able to reproduce it, as this pipeline has run for tens of thousands of runs without this type of timeout, and I'm not seeing it often.

So I'm hoping you might be able to shed some light on circumstances where the timeout would come.. though maybe I should be asking in Terraform core? It seems like the timeout is coming from Terraform waiting on the plugin (as opposed to the plugin saying "I can't reach nomad").

**Comment by lgfa29** [comment] 2021-01-21 23:31
Thanks for the extra info @ketzacoatl.

Looking through Terraform repo I found this issue which describes the same problem in other providers as well: https://github.com/hashicorp/terraform/issues/25133

The latest theory seems to point to open bug on Go 1.14, which is also the version we use to build the Nomad provider.

I've subscribe to that issue and will follow-up if there's any update.

Since it seems like an upstream issue I will close this for now, but feel free to reach out anytime.

**Closed by lgfa29** 2021-01-21 23:31 UTC
Labels: stage/needs-investigation, theme/provider, type/bug

**Comment by ketzacoatl** [comment] 2021-01-21 23:32
That's great, thank you for the info and for staying on top of those details @lgfa29!

**Comment by lgfa29** [comment] 2021-03-09 23:41
Hi @ketzacoatl,

I haven't heard anything from the Terraform upstream team or any other user experiencing a similar issue. 

Since it's been happening more often, would it be possible to capture some extra logs using `TF_LOG=TRACE` now?

**Comment by ketzacoatl** [comment] 2021-03-10 05:07
> Since it's been happening more often, would it be possible to capture some extra logs using TF_LOG=TRACE now?

This is in CI, but yea, I could get the log saved as a file artifact and wait until a run hits this timeout again.

**Comment by lgfa29** [comment] 2021-03-10 15:30
> > Since it's been happening more often, would it be possible to capture some extra logs using TF_LOG=TRACE now?
> 
> This is in CI, but yea, I could get the log saved as a file artifact and wait until a run hits this timeout again.

Thank you. I understand that running debug logs on CI is not a good thing, but without being able to reproduce it we would need more information.

We appreciate all your help on this issue!

**Comment by ketzacoatl** [comment] 2021-04-06 13:21
Just a quick note to update: I have not yet made any progress enabling debug logs in our CI setup. I need to do this on a project that is not so critical, and haven't scoped out time for the updates.

**Comment by lgfa29** [comment] 2021-04-06 14:35
No problem @ketzacoatl 🙂 

Thanks for the update!
